### ISSUE TITLE
acl not saved

### ISSUE THREAD

**Issue by lublak** [drakkan/sftpgo#1043]
currently i try to create acls to disable all access for all folders. But allow one folder (the ftp folder)

![image](https://user-images.githubusercontent.com/44057030/199957911-815cbd55-7227-41b4-9416-8e6489099c52.png)

If i press submit it works fine. But if i go back to the user settings its empty:

![image](https://user-images.githubusercontent.com/44057030/199958120-041b5cfc-2cb3-4835-8c7b-333d18f2640b.png)

**Comment by drakkan** [comment]
No pattern is specified and so the ACL are ignored, maybe you want something like this

![Schermata del 2022-11-04 13-41-58](https://user-images.githubusercontent.com/553263/199975199-8064dc11-43d2-4d40-9174-7e8138180187.png)

if so you have also to set the start directory to `/ftp`

**Comment by lublak** [comment]
@drakkan That works :)
Well actually I wanted to make all folders invisible except ftp.  (which apparently does not work). But you can navigate if you know what the folder is called anyway.

**Comment by drakkan** [comment]
You can set the start directory to `/ftp`  but if you want to hide everything why not set the home directory to `<base path>/ftp`?

**Comment by lublak** [comment]
@drakkan There is a folder:
"D:/ftp"
But on "D:" there are also other folders.
There is a program that writes to /ftp (it cannot write to a root directory)
But I don't want to have "D:/ftp/ftp".
But I also don't want that everything is visible from "D:". As it is right now it fits.
So nothing needs to be changed here :)

**Comment by drakkan** [comment]
Hi,

I was thinking on how to simplify this use case. I think the best approach is this one

![Schermata del 2022-11-19 12-39-10](https://user-images.githubusercontent.com/553263/202848949-0c4dcada-e97e-4b5b-9eb4-86b4e65dbcb9.png)

This one line [change](https://github.com/drakkan/sftpgo/commit/81c693de4e16cfafb40bc8a0cc5fb28503e61ab5#diff-d48bed73cb243b5300108a318eea6494652d40093322e498e5fd5d098725ef33L751) is required otherwise you will not be able to browse back to `/`. It will be included in v2.4.2. Of course you can also keep your current approach

**Comment by lublak** [comment]
@drakkan Oh I have not seen your message. But I will try it the days:) thank you.
