### ISSUE TITLE
Subsystem Permission Denied

### ISSUE THREAD

**Issue by 1Butcher** [drakkan/sftpgo#1096]
Hello,

First of all, I really appreciate the work on this project. It's fantastic!

I'm continuously receiving permission denied errors, while creating folders or files via the web UI. Unfortunately, the log file is not does not offer additional details.

I configured the server in a way that it acts as subsystem to my ssh server like you described in the [docs](https://github.com/drakkan/sftpgo/blob/main/docs/sftp-subsystem.md) .

Is this setup supposed to work also via the web UI provided the sftpgo username equals the system user's.

I can confirm that the setup works as expected when connecting via CLI and sftp. The log displays the instantiation of the subsys process and uploading files works without permission errors.

The issue is not urgent, but I'd appreciate if someone can help me with it. I'm happy to share the logs if necessary.

Thank you!

**Comment by drakkan** [comment]
Hello,

in subsystem mode SFTPGo is started by OpenSSH on demand as the authenticated user, there is no web UI and many SFTPGo features are not available.

I guess you are running another SFTPGo instance as service but since it runs as the `sftpgo` system user it cannot write to your system users home directories. If this is the case you can run this SFTPGo instance as root and map the proper UID/GID for the users you create from the web UI.

**Comment by 1Butcher** [comment]
Hi @drakkan

Sorry for misunderstanding the use cases. You're right, that's how I set it up. I will try your suggestion and come back to the issue.

Thanks for the fast response
