### ISSUE TITLE
Getting Started guide for basic sftp setup

### ISSUE THREAD

**Issue by codinted** [drakkan/sftpgo#118]
Hi,
I want to use sftpgo to setup sftp server with multiple sftp accounts with some common subdirs.
Currently, this is done with  openssh. I'm confused how sftpgo relates to openssh setup.

Do we need to create each linux user for sftpgo user?
Do we need to create home dirs and subdirs for each user before they can be specified in the account creation UI?
Can we create a user encompassing all other users kinda like master user?

Question related sftgo project.
Is there a community channel where we can discuss the basic questions or problems we face while implementing?

**Comment by drakkan** [comment]
> Hi,

Hi

> I want to use sftpgo to setup sftp server with multiple sftp accounts with some common subdirs.
> Currently, this is done with openssh. I'm confused how sftpgo relates to openssh setup.
> 

SFTPGo implements the same SFTP protocol as OpenSSH, so any SFTP client that works with OpenSSH should also work with SFTPGo

> Do we need to create each linux user for sftpgo user?

This is not required. SFTPGo uses virtual users stored inside a data provider (SQLite, MySQL, PostgreSQL, bolt, memory). You can assign a system UID/GID to one or more virtual users if you want to configure SFTPGo this way. In the simplest setup you can map all the users to the system account that runs SFTPGo. Permissions, for the defined users, are virtual too

> Do we need to create home dirs and subdirs for each user before they can be specified in the account creation UI?

This is not required, the home directory is automatically created at the first login (the user that runs SFTPGo needs system permissions to create these folders)

> Can we create a user encompassing all other users kinda like master user?
> 

If I correctly understand what you mean, you can create, for example, a `master` user and define its home dir as `/home/sftpgo/master` for the other users you can define their home dir as `/home/sftpgo/master/user1`, `/home/sftpgo/master/user2` and so on. A such setup could be simplified defining a [users_base_dir](https://github.com/drakkan/sftpgo/blob/master/docs/full-configuration.md)

> Question related sftgo project.
> Is there a community channel where we can discuss the basic questions or problems we face while implementing?

Currently no, for now please open github issues for asking questions, in future if the number of questions will grow I'll evaluate a google group or something similar.

Please try to read the main [README](https://github.com/drakkan/sftpgo/blob/master/README.md) and some more specific docs such as the [service setup guide](https://github.com/drakkan/sftpgo/blob/master/docs/service.md).

Anyway to test sftpgo you can follow these simple steps:

```
mkdir sftpgo
cd sftpgo
wget https://github.com/drakkan/sftpgo/releases/download/0.9.6/sftpgo_0.9.6_linux_x86_64.tar.xz
tar xvf sftpgo_0.9.6_linux_x86_64.tar.xz
./sftpgo initprovider
./sftpgo serve
```

and the create users using the built-in [web interface](http://localhost:8080/web/users)

I'm doing my best to improve the docs but some things that for me, who wrote the code, are obvious may not be so obvious for a user, so if you think that the docs could be improved please send a pull request. 
I will be also glad to link external resources/howto too, thanks!

**Comment by codinted** [comment]
Hey man!
Much thanks :) 
Totally understand. I was unsure about using issues to ask questions. I already installed Sftpgo and it is working well. 
So the User-hierarchy can be managed by designing the directory structure, sounds good.
Will let you know how it worked out and if face any difficulties, will also try to create how-to.
Thanks again :)

**Comment by nop33** [comment]
Hello @drakkan,

I took the liberty of asking for support in this issue since you encouraged _codinted_ to ask questions in GitHub issues. The information in this issue is helpful.

I am trying to set up my SFTPGo server to meet the following requirements:
1. A staff (non-tech) employee can login to the FTP server (through FileZilla), create folders and upload files.
2. The same staff employee should be able to create virtual users and give them access to the folders they have created
3. The virtual users should be able to:
    1. access only the folders/items they have access to
    2. can only see the contents of the folders they have access to and download

Based on your answers above, I figured that the simplest way I can achieve it following these steps:
1. SSH to the server and manually create the `/home/sftpgo` directory
2. Set the `/home/sftpgo` directory as the `users_base_dir` in `/etc/sftpgo/sftpgo.json`
3. Give the user who runs SFTPGo (`sftpgo`) system permissions so that it can create the home folders of the virtual users when they login for the first time
4. Login to the Web Admin interface and
   1. create a virtual user called **staff** and give it all permissions (*) (to meet requirement 1)
   2. create a virtual user called **vuser1** and give only the permissions to **list, download** (to meet requirement 3.2)
5. Login with the **staff** virtual user via FileZilla (so that the `/home/sftpgo/staff` folder gets created) and through FileZilla's interface create a folder called `/home/sftpgo/staff/mapped`
6. Login to the Web Admin interface, edit the **vuser1** user and add the virtual folder with the mapping `/vfolder::/home/sftpgo/staff/mapped` (to meet requirement 3.1)
7. The **vuser1** can now login to the server and access the contents of the `/vfolder` which correspond to the contents of the `/home/sftpgo/staff/mapped` folder

My first question is: does the above procedure look correct to you?

My second question has to do with creating the home dirs of the virtual users:

To do step 3, I did this:
```
$ sudo usermod -aG sudo sftpgo
```

I got stuck at step 5. When I login with the virtual user called **staff**, I see this error in the logs:
```
Oct 06 14:32:42 ftp-staging sftpgo[3211]: {"level":"debug","time":"2020-10-06T14:32:42.459","sender":"osfs","connection_id":"58741a2261f5638c1d63637cc31aaeb34c3c349f2b72e3d2fd0a569740953da1","message":"root directory \"/home/sftpgo/staff\" for user \"staff\" does not exist, try to create, mkdir error: mkdir /home/sftpgo/staff: permission denied"}
```

Seems like the `sftpgo` user doesn't have the right permissions...

_Apologies for the long post, I promise I'll write a **how-to** guide once I succeed meeting my requirements 😄_

**Comment by drakkan** [comment]
Hi,

if you installed from a distro package, for example a deb or pkg, the sftpgo user has `/var/lib/sftpgo` as home dir and it already has the appropriate filesystem permissions on this dir. 

If you set the users base dir as I do for the [Arch Linux package](https://aur.archlinux.org/cgit/aur.git/tree/sftpgo.json?h=sftpgo-git#n83) you can simply create new users without the need to login to the server and create folders/change system permissions.

I should update the default configuration for deb/rpm packages to match the Arch PKGBUILD

**Comment by nop33** [comment]
Yes, I used the deb distro package. OK, I'll set the `users_base_dir` to `/var/lib/sftpgo/users` and move from there. Thank you so much for the speedy reply

**Comment by nop33** [comment]
It worked :) After setting the `users_base_dir` to `/var/lib/sftpgo/users` and logged in into the server with the **staff** virtual user, the `/var/lib/sftpgo/users` and the `/var/lib/sftpgo/users/staff` were both created 🎉 

I created a folder there and uploaded a file in it and created the mapping to a virtual folder. After logging in into the server with the **vuser1** user now, I could only see this virtual folder and the file. Success 🎉 

> I should update the default configuration for deb/rpm packages to match the Arch PKGBUILD

I believe if you do the above there's no need for a how-to, that's the point I was stuck at. And I only now noticed the last line of this [how-to](https://github.com/drakkan/sftpgo/blob/master/docs/howto/postgresql-s3.md) document. Thanks again for the great work and support, much obliged!

**Comment by drakkan** [comment]
> It worked :) After setting the `users_base_dir` to `/var/lib/sftpgo/users` and logged in into the server with the **staff** virtual user, the `/var/lib/sftpgo/users` and the `/var/lib/sftpgo/users/staff` were both created 
> 
> I created a folder there and uploaded a file in it and created the mapping to a virtual folder. After logging in into the server with the **vuser1** user now, I could only see this virtual folder and the file. Success 
> 
> > I should update the default configuration for deb/rpm packages to match the Arch PKGBUILD
> 
> I believe if you do the above there's no need for a how-to, that's the point I was stuck at. And I only now noticed the last line of this [how-to](https://github.com/drakkan/sftpgo/blob/master/docs/howto/postgresql-s3.md) document. Thanks again for the great work and support, much obliged!

I just changed the default configuration, thank you for noticing this
