### ISSUE TITLE
New release? 

### ISSUE THREAD

**Issue by LiadDrori** [drakkan/sftpgo#137]
Hello,

We are using the docker image and We want to lock the image to a specific version, but the latest version is too old and missing features.
When will a new release be available?

**Comment by drakkan** [comment]
Hi,

this is my current plan:

1) I'm working to improve recursive rename/copy permissions check, this should ship soon.
2) we need a new GitHub action that automatically build the release for Linux, macOS and Windows as soon as a new tag is pushed, I don't want to manually build new releases anymore
3) there are some small inconsistencies that I need to analyze and fix, for example used quota can be configured on folder add, I  think that this behaviour is not correct
4) I need to do some manual testing, for example for the dump/load feature

Optional but nice to have:

1) There are some pull requests for dependencies that I'm monitoring, for example 
  - [this one](https://github.com/aws/aws-sdk-go/pull/2653) would allow rename for file > 5GB on S3,
  - [this one](https://code-review.googlesource.com/c/gocloud/+/56712) would improve GCS performance

2) a feedback for my patch to [crypto/ssh](https://go-review.googlesource.com/c/crypto/+/227781) would be useful to have before the next release, SFTPGo Git master already uses it
3) my [performance patch](https://github.com/pkg/sftp/pull/344) for pkg/sftp was approved but not yet merged, this patch is in SFTPGo Git master since some months, it should be well tested now

I'm quite busy with my daily work in this period, I don't have a temporal plan for now, meantime you can help to test the current Git master and report any issues you find,

thank you for your interest in SFTPGo.

**Comment by drakkan** [comment]
version 1.0.0 is now available
