### ISSUE TITLE
[Bug]: User directory not deleted on User deletion

### ISSUE THREAD

**Issue by Joshua2504** [drakkan/sftpgo#1379]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

If I delete a user, his user directory isn't being deleted.

### Steps to reproduce

1. Create a user and upload files.
2. Delete the user via UI.
3. User files are still present on the system.

### Expected behavior

User files should be deleted when deleting a user.

### SFTPGo version

2.5.4-cc381443-2023-07-15T07:58:42Z

### Data provider

Local

### Installation method

Community Deb package

### Configuration

nothing special

### What are you using SFTPGo for?

Enterprise

**Comment by Joshua2504** [comment]
Why will this not be fixed or changed?
If creating a new user with the same name, the user will be able to access the files of the previous user.

**Comment by drakkan** [comment]
I appreciate you stating your enterprise usage and not writing student, home user etc.
I don't mean to be rude but I don't have the time/motivation to explain how to use SFTPGo and please note that I am taking my time to reply to you instead of ignoring you like you ignore the support policy.
We no longer provide free step-by-step support. Thanks for understanding.

**Comment by Joshua2504** [comment]
I'm not asking for a step-by-step guide. I assume that there's a documentation about this then. But where? I can't find anything about it in the docs.
