### ISSUE TITLE
Feature request: configurator

### ISSUE THREAD

**Issue by wkoszek** [drakkan/sftpgo#145]
# Feature

Add a simple text-based auto-configurator

# Problem

There's a lot of config options here, and limited number of examples. It'd be amazing if the tool came with a simple dialog-based config, so that by doing `sftpgo initprovider`, I could get a JSON config set for my required settings.

# Target

Go from zero to PostgreSQL-based auth with S3 as storage engine in 5min. :-)

# Inspiration

`rclone` does a great job at this. It supports large number of complex systems, yet the config of it makes it very easy for a non-expert to configure stuff properly.

Another configurator is in `aws configure`

I'm sure I'm missing something here, but maybe others will chime in.

**Comment by drakkan** [comment]
Hi,

this could be a nice addition, a CLI command that allows to generate the SFTPGo configuration file based on the answers to some questions.

Anyway after the configuration, to create an S3 user you need to use the built-in web interface or the REST API (directly or via the REST API CLI script).

**Comment by drakkan** [comment]
Hi,

I did some tests to evaluate the implementation of this feature.

We could use a library as helper for asking questions, for example [survey](https://github.com/AlecAivazis/survey), [go-prompt](https://github.com/c-bata/go-prompt) and [promptui](https://github.com/manifoldco/promptui) look good, anyway they don't work on some shells, for example on Git bash for Windows.

Something like this one:

```
fmt.Print("Enter text: ")
var input string
fmt.Scanln(&input)
fmt.Println(input)
```

is not so fancy but it works in every shell.

We could ask some basic questions such as the data provider configuration parameters, the hook to execute after a file upload and so on.

After configuring the data provider we could ask to verify the connection and initialize the provider if needed.

As a final step we can allow the user choose the preferred configuration format (JSON,YAML,HCL,TOML) and save the new configuration file.

We can add a new subcommand for this for example `sftpgo gen config`.

I understand that an interactive CLI that helps to generate a configuration file instead of editing it manually could be useful, however this implementation requires a fair amount of work and I'm not motived enough to develop it myself, sorry.

I will be glad to review and merge a well written pull request. Thank you!

**Comment by wkoszek** [comment]
@drakkan I think it's a fairly big feature, but the libraries you've found look very reasonable. I like the way AWS CLI has `aws configure` and we could model this stuff after AWS.

Would you be willing to change docs + make modifications in SFTPGO to encompass this change? What I was thinking about:
- instead of having docs the way they are now, we could have a `DOCS.yml` file with all the config entries there.
- all the config entries could have a "group" e.g.: backend / REST API etc.
- all the entries would have short/long docs
- that way, docs could be auto-generated from this YAML file and never out of date

This `DOCS.yml` would be easy to iterate through. During `sftpgo configure`, the algo could look like this:

```
config = read default config file shipped as file or maybe embedded in sftpgo.
yaml = open DOCS.yaml
for each group G in yaml:
   print Would you like to configure G.name functionality?
   if yes:
      print G.desc [default: G.default], valid options: G.validOptions
      make a choice
      put that choice in a config hierarchy appropriate to this G
```

Is there a reason why you decided to hard-code all the defaults? I quickly glanced at `init()` -- I might be wrong here. I was wondering if you could just get Viper to fetch a default config file from in-memory file, and then just overwrite stuff that needs changing. I'm thinking of a usual UNIX "tradition", where you get a file shipped with all sorts of things commented out, but whatever is there is a default value which a program is running with.

**Comment by jovandeginste** [comment]
Just my 2c: I use promptui in some projects, and while it has some quirks, it works sufficiently well. I chose that one over the other 2 back when I was looking.

**Comment by folknor** [comment]
Just to state the obvious for anyone who stumbles across this: any potential configurator;
1. Does not need to be written in the same programming language as the application its supporting
2. Does not need to be part of this repository
3. Does not need to work on all platforms
4. Does not need to handle everything configurable, but can use sensible defaults or leave the rest up to the user
5. Can hardcode every config setting and their values and help texts initially, and evolve over time if needed, and just write `works with sftpgo v2.011`, or whatever version

So there's no reason to plan ahead in this ticket or get any input from drakkan or any other sftpgo dev. You can just start working on it on your own, in your own choice of language, in your own repository, and make it work like you want. And then the projects can converge over time if convenient, or help eachother out, or not.

**Comment by drakkan** [comment]
Hi,

if someone is still interested in this feature a PR is welcome, thank you
