### ISSUE TITLE
Password + Public Key with External Auth expected response

### ISSUE THREAD

**Issue by FedeFressiel** [drakkan/sftpgo#1599]
### Is your feature request related to a problem? Please describe.

I found your project amazing. While doing R&D for a project that requires a password and public key validation via an external auth I couldn't understand how to enforce it.
Sometimes I receive multiple Public Key validations at the endpoint and sometimes a username validation. After the first username password validation, it seems to get cached, even after I play with the file `sftpgo.json` or when I return `external_auth_cache_time` in `0` or `1`.
I need to guarantee that the two authentication methods are being called. Should both return a successful user response? 

### Describe the solution you'd like

An example or documentation on how to force password and public key security with external auth.
The relevant fields `SFTPgo.json` and the expected answers for both auth calls.

### What are you using SFTPGo for?

Professional user, 1 person business

**Comment by drakkan** [comment]
The issue is on your side. This use case works fine.

If you want to try to get free support, please open a discussion and hope that someone has the time and motivation to help you.

Since I'm trying to make the project long-term sustainable and I also want to keep it fully open source, I don't provide free support any longer, sorry. See also [this comment](https://github.com/drakkan/sftpgo/discussions/1601#discussioncomment-9214638)
