### ISSUE TITLE
[Bug]: Columns "Name" is aligned to the right if every folder inside has a number as name

### ISSUE THREAD

**Issue by Mathieu-COSYNS** [drakkan/sftpgo#1628]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

Columns "Name" is aligned to the right if every folder inside has a number as name

### Steps to reproduce

1. `docker pull drakkan/sftpgo:v2.6.0-alpine-slim`
2. `docker run --rm --name some-sftpgo -p 8080:8080 drakkan/sftpgo:v2.6.0-alpine-slim`
3. Create a new user with no files
4. Log with this new user
5. Create a folder named with any number (for example `1`)

![image](https://github.com/drakkan/sftpgo/assets/64072917/1e11735d-b15a-441d-a87e-8cfd85eab005)

### Expected behavior

The column "Name" is aligned to the left

![image](https://github.com/drakkan/sftpgo/assets/64072917/53b281cb-7ec7-427e-a685-3783b9bd3a27)

### SFTPGo version

v2.6.0

### Data provider

/

### Installation method

Community Docker image

### Configuration

config

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by drakkan** [comment]
This issue affects all datatables and can be resolved by adding the "text-start" css class to the "th" elements.

It could also be a bug in the datatables itself or in the UI theme, further investigations are needed.
Since this problem is very rare, I prefer to wait a while to see if it will be fixed next time we update the theme and/or the datatables library
