### ISSUE TITLE
[Bug]: proxy_allowed not working in latest image

### ISSUE THREAD

**Issue by ziporah** [drakkan/sftpgo#1671]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

The proxy_protocol allowed isn't working in the latest version.

### Steps to reproduce

1. configure sftp with proxy allowed
```
    Environment:
      SFTPGO_COMMON__PROXY_ALLOWED__0:             193.58.149.121
      SFTPGO_COMMON__PROXY_ALLOWED__1:             193.58.149.122
      SFTPGO_COMMON__PROXY_PROTOCOL:               2
      SFTPGO_COMMON__PROXY_SKIPPED__0:             10.241.253.0/24
```
2. Run sftp command trough proxy with proxy protocol configured
3. Log shows error
```
{"level":"debug","time":"2024-06-26T08:12:46.238","sender":"sftpd","message":"failed to accept an incoming connection from ip \"193.58.149.121\": proxyproto: upstream connection sent PROXY header but isn't allowed to send one"}
{"level":"debug","time":"2024-06-26T08:12:46.238","sender":"connection_failed","client_ip":"193.58.149.121","username":"","login_type":"no_auth_tried","protocol":"SSH","error":"proxyproto: upstream connection sent PROXY header but isn't allowed to send one"}
```

### Expected behavior

the pod should accept the connection

### SFTPGo version

2.6.x image

### Data provider

sqlite

### Installation method

Community Docker image

### Configuration

    Environment:
      SFTPGO_COMMON__PROXY_ALLOWED__0:             193.58.149.121
      SFTPGO_COMMON__PROXY_ALLOWED__1:             193.58.149.122
      SFTPGO_COMMON__PROXY_PROTOCOL:               2
      SFTPGO_COMMON__PROXY_SKIPPED__0:             10.241.253.0/24
      SFTPGO_DEFAULT_ADMIN_USERNAM:  username
      SFTPGO_DEFAULT_ADMIN_PASSWORD: password

### Relevant log output

```shell
{"level":"debug","time":"2024-06-26T08:12:46.238","sender":"sftpd","message":"failed to accept an incoming connection from ip \"193.58.149.121\": proxyproto: upstream connection sent PROXY header but isn't allowed to send one"}
{"level":"debug","time":"2024-06-26T08:12:46.238","sender":"connection_failed","client_ip":"193.58.149.121","username":"","login_type":"no_auth_tried","protocol":"SSH","error":"proxyproto: upstream connection sent PROXY header but isn't allowed to send one"}
```

### What are you using SFTPGo for?

Enterprise

### Additional info

It works fine with the 2.5.x image

**Comment by nzx-jsantaana** [comment]
As a supporting point to this, we're using 2.6.2-1 on RHEL 8, from the official RPM repos.  Our testing shows that the proxy_* settings don't work if set in an environment file (either `sftpgo.env` or an `env.d/` fragment), but _do_ work if set directly in `sftpgo.json`.

I don't know if that's an option for Docker image users, and it's not desirable long-term for RPM package users either (editing `sftpgo.json` counts as modifying a package-owned file, so you end up with an `sftpgo.json.rpmnew` on upgrades rather than updates to the base config being applied automatically.)  But it may be a workaround for some people, and either way it's relevant information that I hope helps identify the bug.

Additional info:
* I tried setting the vars in both sftpgo.env and an env.d/ fragment, both with and without the [common] section included, ie `SFTPGO_COMMON__PROXY_PROTOCOL=1` and `SFTPGO_PROXY_PROTOCOL=1`.
* When a fragment was used, the logs showed "set env vars from file /etc/sftpgo/env.d/enable-haproxy.env" as expected; no errors were seen in any case.
* I don't see any option to log which vars are set or attempted to be set, only the "processed this file" messages.  If there's something I can set for more detailed debugging, I'm happy to do so if it'll help.

**Comment by n0v1** [comment]
Did you try setting the env var like this?:
`SFTPGO_COMMON__PROXY_ALLOWED=1.2.3.0/24,4.5.6.0/24`

This was working in 2.5.4 and seems to still work in 2.6.2 (look for logs which contain "ProxyAllowed" during startup).

**Comment by nzx-jsantaana** [comment]
I thought I had, but I must have tried that form only when I didn't have the `COMMON__` part in the variable name; testing shows that it does in fact work correctly.  Thank you for the assistance.  (Also, I found it easier to look for "ProxyProtocol" in the startup logs; there are separate "ProxyAllowed" values in various sub-server configurations which get in the way of finding the common-context one.)

@ziporah This form worked for me on 2.6.2, as suggested by n0v1:
```
SFTPGO_COMMON__PROXY_PROTOCOL=1
SFTPGO_COMMON__PROXY_ALLOWED=1.2.3.4, 5.6.7.8
```
results in the startup logs containing
... `ProxyProtocol:1 ProxyAllowed:[1.2.3.4  5.6.7.8]` ...
(commas get converted to spaces, which is why the double space in the list; it still works.  You can quote the list too if you like.)

The form you listed:
```
SFTPGO_COMMON__PROXY_ALLOWED__0:             193.58.149.121
SFTPGO_COMMON__PROXY_ALLOWED__1:             193.58.149.122
SFTPGO_COMMON__PROXY_PROTOCOL:               2
```
sets the protocol value but not the allowed list:
... `ProxyProtocol:2 ProxyAllowed:[]` ...
It looks like the ProxyAllowed values may have been a struct in the earlier version, but now they're a plain list so the `__X` indexing doesn't work any more; that's just a guess, though.  I haven't actually checked the older version.

**Comment by drakkan** [comment]
> It looks like the ProxyAllowed values may have been a struct in the earlier version

It was the same also in older versions, so this invalid issue can be closed. Thank you
