### ISSUE TITLE
[Bug]: Permission Denied While Uploading Files To GCS Bucket

### ISSUE THREAD

**Issue by gouravjoshicldcvr** [drakkan/sftpgo#1686]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

I have installed sftpgo on a Ubuntu server and created a user with a GCS bucket backend.
I have used the service account key file which has full access to the GCS bucket but cannot upload files.
I can read files and folders from the bucket and I can delete those files and folders but not able to delete them and same service account is working with another sftp server.

In logs I am getting below error 

{"level":"debug","time":"2024-07-03T18:01:39.115","sender":"HTTP","connection_id":"HTTP_cq2p40s50djsgr8e2rj0","message":"connection added, local address \"10.2.0.44:8080\", remote address \"10.2.0.11:41808\", num open connections: 1"}
{"level":"error","time":"2024-07-03T18:01:39.215","sender":"HTTP","connection_id":"HTTP_cq2p40s50djsgr8e2rj0","message":"**could not open file \"test1/image (4).png\"** **for reading: open /pipefile1467703216: permission denied**"}

### Steps to reproduce

1.Setup sftpgo on ubuntu
2.Added GCS as backend for user
3.upload a file

### Expected behavior

File should be uploaded without any error

### SFTPGo version

SFTPGo 2.6.2

### Data provider

Sqlite

### Installation method

Community Deb package

### Configuration

Default Config 
Installed via sudo apt install sftpgo

### Relevant log output

```shell
{"level":"debug","time":"2024-07-03T18:01:39.115","sender":"HTTP","connection_id":"HTTP_cq2p40s50djsgr8e2rj0","message":"connection added, local address \"10.2.0.44:8080\", remote address \"10.2.0.11:41808\", num open connections: 1"}
{"level":"error","time":"2024-07-03T18:01:39.215","sender":"HTTP","connection_id":"HTTP_cq2p40s50djsgr8e2rj0","message":"**could not open file \"test1/image (4).png\"** **for reading: open /pipefile1467703216: permission denied**"}
```

### What are you using SFTPGo for?

Medium business

### Additional info

NA

**Comment by Tsafaras** [comment]
It works for me and I've done the following, in a fresh installation.

Used `docker` image with this compose file:
```yaml
services:
  vc-sftp:
    image: drakkan/sftpgo:v2.6.3-alpine
    ports:
      - 2022:2022
      - 8080:8080
    env_file:
      - .env
    environment:
      - SFTPGO_DEFAULT_ADMIN_USERNAME=admin
      - SFTPGO_DEFAULT_ADMIN_PASSWORD=admin
      - SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN=true
```

- Set up a user using WebAdmin, allowing it to access to a GCS bucket, providing the SA with the `Storage Object User` role on _that_ bucket.
- Then ran `sftp` as that user for a file and it worked.

![image](https://github.com/user-attachments/assets/ea50bb6b-9ee4-4819-b660-152ba699a614)


![image](https://github.com/user-attachments/assets/31015cc5-00d8-45ea-8858-a00b6d203203)

I also see the error says "could not _OPEN_ file", so maybe you're calling `put FILE` instead of `put ./FILE`?

**Comment by drakkan** [comment]
This is just a support request, not a bug

**Comment by mehdicopter** [comment]
Hi, I do have the same error, I am running `sftpgo` in kubernetes environment.
I am using Workload Identity with the role `Storage Object User`

**Comment by zpmdinh** [comment]
@mehdicopter I've encountered the same issue, as I'm using Workload Identity in a GKE cluster and assigning a service account as Storage Object Admin; however, it's still unable to perform the "download" and "view" operations on the file from the bucket.
Is there any luck for fixing this issue?

**Comment by zpmdinh** [comment]
btw @mehdicopter I know the root cause.
The reason is that your k8s pod needs to set podSecurityContext to root user or any user with has permission to read/write in the local disk, since all operations should be handled in the local disk of the container as temp before proceeding with any downloading/uploading, etc.

**Comment by drakkan** [comment]
For those interested, our [Enterprise edition](https://docs.sftpgo.com/enterprise/changelog/) can be configured to avoid using unlinked disk files during transfers to cloud storage backends.
