### ISSUE TITLE
Consider using gocloud.dev/blob for object stores

### ISSUE THREAD

**Issue by sagikazarmark** [drakkan/sftpgo#172]
Looking at the implementations, it should be possible to use https://gocloud.dev/howto/blob for interacting with object stores. I haven't looked at it too deeply though, so I could be wrong, but it could help reduce the amount of maintained code.

If you like the idea, I could take a look at it.

**Comment by drakkan** [comment]
Hi, 

this could be a good idea and we should get for free Azure support that is something I would like to add at some point. 

However I don't want to loose the abilitity to customize things for example for S3 we can customize upload concurrency  or in future we want to support versioning.

I need some time to better investigate pro and cons thank you for the suggestion!

**Comment by sagikazarmark** [comment]
Sure!

S3 is probably widespread enough to warrant a separate implementation.

**Comment by drakkan** [comment]
Hi,

I'm using gocloud in a private project and it works well! 

However switching to gocloud we lose low level control, for example:

- flat object list is not supported, we request a flat list in several place inside the sftpgo implementation, for example to update quota and to implement walk, a flat list is very convenient in this case since we haven't to recurse inner directories ourself
- it is more difficult to handle edge cases, see [here](https://github.com/drakkan/sftpgo/blob/master/vfs/azblobfs.go#L245). Gocloud use the high level api `UploadStreamToBlockBlob`, in sftpgo we use the low level upload API

An interesting thing in gocloud is the quoting of special characters, I should do something similar in sftpgo as well, removing the quoting for the trailing "/" which will cause compatibility problems with things like s3fs.

Since I am now using gocloud myself, I will monitor how it evolves, but for now I prefer to stick to a low level implementation within SFTPGo, thanks
