### ISSUE TITLE
[Bug]: admin cannot login after fresh install (The form token is not valid)

### ISSUE THREAD

**Issue by injaan** [drakkan/sftpgo#1816]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.

### Bug description

I have freshly installed SFTPGo on Ubuntu 22. After setting up the admin user and creating a password for the first time, I attempted to log in to the admin panel. However, when I try to log in with my admin credentials, I encounter the following error: “The form token is not valid”

### Steps to reproduce

1. Install SFTPGo on Ubuntu 22.04 using "apt install sftpgo" as root user
2. reverse proxy 8080 to ftp.mydomain.com using nginx 
3. access to my domain (my domain is behind cloudflare proxy:https )
4. create an admin user and set the password during the first time setup.
5. Attempt to log in to the admin panel with the created admin credentials.
6. Encounter the “The form token is not valid” error.

### Expected behavior

Successful login

### SFTPGo version

SFTPGo 2.6.3-cf3e1d3e-2024-11-15T16:58:44Z

### Data provider

local

### Installation method

Community Deb package

### Configuration

no customization

### Relevant log output

```shell
Nov 23 07:26:21 ubuntu-8gb-hel1-1 sftpgo[8234]: {"level":"debug","time":"2024-11-23T07:26:21.453","sender":"httpd","local_addr":"[::1]:8080","method":"POST","proto":"HTTP/1.1","remote_addr":"[::1]:44714","request_id":"ubuntu-8gb-hel1-1/mT6MWW4Jyg-000001","uri":"http://ftp.mydomain.mn/web/admin/login","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36","resp_status":200,"resp_size":28767,"elapsed_ms":6}
Nov 23 07:26:28 ubuntu-8gb-hel1-1 sftpgo[8234]: {"level":"debug","time":"2024-11-23T07:26:28.443","sender":"httpd","message":"error validating CSRF token IP audience"}
Nov 23 07:26:28 ubuntu-8gb-hel1-1 sftpgo[8234]: {"level":"debug","time":"2024-11-23T07:26:28.445","sender":"httpd","local_addr":"127.0.0.1:8080","method":"POST","proto":"HTTP/1.1","remote_addr":"127.0.0.1:45002","request_id":"ubuntu-8gb-hel1-1/mT6MWW4Jyg-000002","uri":"http://ftp.mydomain.mn/web/admin/login","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36","resp_status":200,"resp_size":28775,"elapsed_ms":3}
```

### What are you using SFTPGo for?

Private user, home usecase (home backup/VPS)

**Comment by injaan** [comment]
I've disabled cloudflare proxy and accessed http protocol and getting still same error

**Comment by P4r4n01dB34r** [comment]
Hi, i had today the same error after setting up the login with my oidc.
i added the following variable to my httpd.env and it is now working:

SFTPGO_HTTPD__BINDINGS__0__TOKEN_VALIDATION: "1"

**Comment by injaan** [comment]
@P4r4n01dB34r Hi, where does this httpd.env file located?

**Comment by injaan** [comment]
@P4r4n01dB34r thank you. It's done

**Comment by MSpaceDev** [comment]
I wanted to add to the conversation for anyone who finds this issue in the future.

The solution provided by @P4r4n01dB34r using `TOKEN_VALIDATION: "1"` does work to resolve the "The form token is not valid" error. However, I believe there's a more secure alternative that addresses the root cause directly without relaxing security settings.

The root cause of the `error validating CSRF token IP audience` log message is that SFTPGo is behind a reverse proxy and sees the IP of the proxy instead of the actual user's IP. The `TOKEN_VALIDATION: "1"` setting likely works by disabling the IP check portion of the CSRF validation.

A more secure approach is to configure SFTPGo to trust your reverse proxy and correctly identify the end-user's IP from the `X-Forwarded-For` header. This keeps the full CSRF IP validation intact. This is done by adding `proxy_allowed` and `client_ip_proxy_header` to the `httpd.bindings` section in `/etc/sftpgo/sftpgo.json`.

**The Solution:**

In your `sftpgo.json`, modify the binding for your HTTP/HTTPS service to include the following settings:

```json
"bindings": [
  {
    "port": 8080,
    // ... your other binding settings ...

    "proxy_allowed": [
      // Add the IP address(es) of your trusted proxy here
    ],
    "client_ip_proxy_header": "X-Forwarded-For"
  }
]
```

**Examples for `proxy_allowed`:**

*   For a standard **Nginx/Apache** reverse proxy on the same machine:
    ```json
    "proxy_allowed": ["127.0.0.1/8", "::1/128"]
    ```
*   For **Cloudflare**, you should use their official list of IP ranges found [here](https://www.cloudflare.com/ips/).
*   For a **Google Cloud External Application Load Balancer** (which was my specific use case), the correct IP ranges are:
    ```json
    "proxy_allowed": [
      "130.211.0.0/22",
      "35.191.0.0/16"
    ]
    ```

After adding these settings and restarting the SFTPGo service, the "form token is not valid" error was resolved, and the application now functions perfectly behind the load balancer while maintaining full CSRF security.

I hope this helps someone else.
