### ISSUE TITLE
ability to toggle alternative languages on/off (or choose which are enabled)

### ISSUE THREAD

**Issue by andy-clapson** [drakkan/sftpgo#1835]
### Is your feature request related to a problem? Please describe.

This isn't a problem, just a configuration option in the nice-to-have category. 

Our use of SFTPGo is English-only, so we don't require any multilingual support, so suppressing the language-chooser on the login screen would be useful.

### Describe the solution you'd like

A configuration option, where a list of supported languages is passed in via an environment variable (or similar). If a single language is passed in, that language would be the only support one - i.e. no chooser.

### Describe alternatives you've considered

Editing the CSS overrides to remove the language chooser from the login template.

### What are you using SFTPGo for?

Medium business

### Additional context

SFTPGo is great! It's a very fine tool and we enjoy working with it.

**Comment by drakkan** [comment]
Hello,

Thanks for the suggestion. It's planned, we just need to find some time to implement the feature

**Comment by drakkan** [comment]
@ralhako someone should contrinute the German translation on [Crowdin](https://crowdin.com/project/sftpgo) first. 

We are unable to independently proofread translations into languages ​​other than Italian, and since none of our commercial users seem to be interested, we will not pay a professional to do so.

We may still consider merging translations into 2.7 as a best effort, once we have implemented a way to disable them, because as you can see they are causing problems for some users and allowing them to be disabled is especially necessary if we decide to accept possible low-quality translations.

**Comment by ralhako** [comment]
I did the translation on Crowdin and am now testing it in SFTPGO. This translation is fine for my volunteers to use STFPGO. If the translation seems professional to me, I will let you know here.

**Comment by drakkan** [comment]
> I did the translation on Crowdin and am now testing it in SFTPGO. This translation is fine for my volunteers to use STFPGO. If the translation seems professional to me, I will let you know here.

Thank you, could you tell us which foundation you work for?
It would be helpful for the project if you could indicate on your foundation's website that SFTPGo is useful to you and/or if we could link your website from this repo.

**Comment by ralhako** [comment]
For now: [https://sftpgo.schwiering-stiftung.de](url)
The translation looks good. I'll now check whether the texts correspond to the program.

**Comment by andy-clapson** [comment]
beautiful! thanks @drakkan ! 👌
