### ISSUE TITLE
Merge full and slim dockerfiles

### ISSUE THREAD

**Issue by sagikazarmark** [drakkan/sftpgo#232]
Sadly I don't have much time to provide a PR at this time, I just wanted to point out that the full and the slim Dockerfiles could be merged together. You could do something like this:

```dockerfile
ARG INSTALL_ADDITIONAL_PACKAGES=false
RUN [[ $INSTALL_ADDITIONAL_PACKAGES == "true" ]]; then install; fi
```

Then you can pass a build arg to build the image with a different build tag.

There are several reasons why you might want to do this:

- currently all those extra layers (switching default users) show up in the image history
- generally speaking less Dockerfiles are more manageable and if someone wants to look into those files, they can see everything in a single file

**Comment by drakkan** [comment]
Hi,

I'm aware of build tags, I used the current mode to improve build speed. As you can see [here](https://github.com/drakkan/sftpgo/runs/1455849660?check_suite_focus=true) slim build take about 20-25 minutes while full less than a minute since it uses the previous build. Using your approach we'll have 4 builds and each one will take about 20-25 minutes.

I see the extra layers in the [image history](https://hub.docker.com/layers/drakkan/sftpgo/edge/images/sha256-d30248325c079b1c79c2620ca62aa5ffefe83352965076eeb28395fbf08fa6dd?context=explore) but they are 0 B, they shouldn't hurt, am I wrong?

**Comment by sagikazarmark** [comment]
There is nothing inherently wrong with them, just the slight inconvenience of having to go through multiple Dockerfiles to understand what's going on.

You could parallelize those builds so they wouldn't take 25 minutes in total.

Anyway, I just wanted to bring this to your attention, feel free to close it.

**Comment by drakkan** [comment]
I leave this issue open for further evaluation, thanks for reporting
