### ISSUE TITLE
Folder Support for S3

### ISSUE THREAD

**Issue by misilot** [drakkan/sftpgo#241]
Hi,

Is it possible to configure an S3 bucket as a virtual folder (be great if you can specify multiple paths as well) that I can share among different users? That way it only needs to be configured once as the bucket level, and multiple users can utilize it.

Thanks!

**Comment by drakkan** [comment]
Hi,

we could add a filesystem configuration to each virtual folder so that we can mount encrypted or cloud backends as subfolders for local filesystems and vice versa. This is something I've been thinking about, see the latest sentence [here](https://github.com/drakkan/sftpgo/blob/master/docs/dare.md). I plan to work on it after completing the current development cycle (so after version 1.3.0). However, even reviewing a PR for this feature would also be really challenging, a sponsorship would be ideal here.

**Comment by perfecto25** [comment]
is it possible to add S3 for users backend, but instead of whole bucket, just a subfolder in the bucket

ie if I have a bucket on S3 called users
in that bucket I have subfolders, joe, mary, bob

can I map user "joe" to bucket

users/joe

I tried playing around with this on the Admin console but cant get this to work.

**Comment by drakkan** [comment]
> is it possible to add S3 for users backend, but instead of whole bucket, just a subfolder in the bucket
> 
> ie if I have a bucket on S3 called users
> in that bucket I have subfolders, joe, mary, bob
> 
> can I map user "joe" to bucket
> 
> users/joe
> 
> I tried playing around with this on the Admin console but cant get this to work.

Hi, a different thing is asked in this thread, please open a separate discussion/issue describing your configuration and including sftpgo logs. In your case you need to set a `Key Prefix` using the SFTPGo admin console, this should work thank you

**Comment by drakkan** [comment]
> Hi,
> 
> Is it possible to configure an S3 bucket as a virtual folder (be great if you can specify multiple paths as well) that I can share among different users? That way it only needs to be configured once as the bucket level, and multiple users can utilize it.
> 
> Thanks!

@misilot if you want to share the same bucket among multiple users assigning a different bucket path to each user without manually creating each user this is already possible since 2.0.x. You can simply create a template, using the web admin, and then import it, you can use the %username% placeholder as key prefix. 

If you need a bulk update you can use a script, [here](https://github.com/drakkan/sftpgo/tree/main/examples/bulkupdate) is an example. 

What's missing is support for mounting an s3 bucket as a virtual path for a local user and nesting local/remote folder as virtual paths in general.

I have no plan to let choose the filesystem provider from a select menu or similar if this is what you mean, please use a template for this use case
