### ISSUE TITLE
AWS S3 storage with empty Key Prefix

### ISSUE THREAD

**Issue by olivierSemet** [drakkan/sftpgo#290]
Hi,

I would like to setup a S3 bucket as storage system for my sftp solution. I tested to create 2 users. Let's say user_1 and user_2. If I leave the parameter "Key Prefix" empty for both, user_1 will get access to user_2's folders and vice versa. So to avoid this behavior, I need to fill the Key prefix but it can lead to an important security concern in a production environment if the sftp administrator forget to  fill the parameter. Is there a way to either:

- Like for local storage, fill automatically the key prefix with the username?
- Configure this parameter as mandatory on the web interface/Rest API with value "" not permitted ? 

Thanks,

**Comment by drakkan** [comment]
Hi,

for local storage the home dir is mandatory, we cannot have a user without a home dir, and we have a specific setting: `users_base_dir` must not be empty otherwise you have to manually set the home for local users too. 

For S3 there are valid use cases where the key prefix must be empty (you want to serve the whole bucket) so it cannot be mandatory. Adding a new settings for this seems overkilling, anyway you can create your users from a template (you need git master for this). Using a template you can set the key prefix to `%username%` and it will be replaced with the username

**Comment by olivierSemet** [comment]
Thank you for the answer. I'll go this way

**Comment by drakkan** [comment]
Great! Please let me know if you find any issues using the new template feature, thanks
