### ISSUE TITLE
can you support for gridfs?

### ISSUE THREAD

**Issue by beanhacker** [drakkan/sftpgo#296]
hi,
   as I have tested mongodb's gridfs, it's download rate can reach to 95M/s, and mongodb itself can store all user info directly,
   so i think support mongodb's gridfs will solve the user data storage in local issure, and directly get and put files into mongodb
   then will no user files in local. and mongodb can backup indenpendent.

**Comment by drakkan** [comment]
Hi,

I don't plan to work on this feature sorry.

SFTP needs random read/write access: suppose you have a 1GB file, an SFTP client can ask to write 32768 bytes at xxxx offset. I think this, while possible, could be problematic using gridfs.

Maybe we could add a new storage backend for that, but we have to implement the directory listing/stat etc. ourself. Do you want to provide a patch? 

Can you please explain why you cannot use one of the supported remote providers if you don't want to use a local filesystem?

Something like OpenStack Swift is more interesting to me. I haven't tested it but it may already work using the S3 backend.

**Comment by beanhacker** [comment]
@drakkan what i should explain is that, i'm in china, many service provider such as twitter, facebook,google and amazon have been walled as they are considered to spread low-level ideas and obtain public information at the same time. so, I want to build the private storage environment.
   can one file have http access right? in the case that i stored one image file by sftps with webrtc or ftps, than i need the file can be accessed by img link in browser with src attr, no need to auth any more.
thanks.

**Comment by drakkan** [comment]
@beanhacker I understand your need and this is the reason I suggested OpenStack Swift

https://github.com/openstack/swift

this way you should be able to build your own private storage environment. Eventually you can use SFTPGo to put files on Swift via SFTP/FTP/WebDAV. I haven't tested Swift myself but since it supports [S3 API](https://docs.openstack.org/swift/latest/s3_compat.html) too it could already work with SFTPGo via the S3 backend. If this doesn't work I could be interested to add support for its native API.

I evaluated mongodb as dataprovider (to store users and folders) in the past. I haven't added support for it since it requires a replica set to support multiple-document transaction.

**Comment by drakkan** [comment]
Please try the suggested solution, gridfs, postgres large object and similar solutions are not planned for now, sorry
