### ISSUE TITLE
http login

### ISSUE THREAD

**Issue by ryjogo** [drakkan/sftpgo#306]
After upgrading from v.1.0.2 to 2.0.1 i can no longer login to the http gui. 

has the format of the users json file changed?

I get: 

`{"level":"warn","time":"2021-02-08T10:50:45.480","sender":"dataprovider_sqlite","message":"error authenticating admin \"admin\": not found: sql: no rows in result set"}
`

**Comment by ryjogo** [comment]
OK, according to this there is a "default admin" user now

https://github.com/drakkan/sftpgo/blob/master/docs/web-admin.md

Which works.. 

I guess i need to update my users backup

**Comment by drakkan** [comment]
Hi,

your users backup should be automatically migrated when SFTPGo loads it. You still need to upgrade it since we only support the previous data format: v2.0.x can load/migrate users from 1.2.x, v2.1.x will load/migrate users from 2.0.x etc.

Regarding the web admin the `auth_user_file` is gone, now admin users are stored inside the data provider and you can assign them permissions. A default admin, with all the permissions, will be created if missing.

You can also use the web admin to backup/restore your data now.

**Comment by ryjogo** [comment]
Great, thanks..
