### ISSUE TITLE
[FR] static HTTP server support

### ISSUE THREAD

**Issue by NightMachinary** [drakkan/sftpgo#339]
Can we have a static HTTP server (ala [this](https://files.zii.lilf.ir/))? Perhaps this can be built into the already existing webDAV server (I have seen webDAV servers that are accessible by a normal browser). This helps for sharing stuff with clients that do not have any pre-installed clients except a simple browser.

**Comment by NightMachinary** [comment]
[**@NightMachinary**](https://github.com/NightMachinary) commented on [Mar 8, 2021, 8:35 PM GMT+3:30](https://github.com/drakkan/sftpgo/issues/339#issue-824760939 "2021-03-08T17:05:36Z - Replied by Github Reply Comments"):
> Can we have a static HTTP server (ala [this](https://files.zii.lilf.ir/))? Perhaps this can be built into the already existing webDAV server (I have seen webDAV servers that are accessible by a normal browser). This helps for sharing stuff with clients that do not have any pre-installed clients except a simple browser.

**Comment by drakkan** [comment]
Hi,

something similar was discussed in the past, see [here](https://github.com/drakkan/sftpgo/discussions/279). I don't have a definite schedule for now.

In the meantime maybe you can try one of the existing web dav browser clients (I haven't tested them). SFTPGo webdav implementation supports has CORS support to help with this.

Anyway webdav is, almost, universally supported without the need to install anything:

- on Linux both nautilus and dolphin support WebDAV
- Windows explorer supports WebDAV
- macOS finder supports WebDAV

on mobile device, probably, a specific app is required

**Comment by orware** [comment]
@NightMachinary,

If this is still of interest to you, I'm not sure if my solution below is exactly what you're looking for since your needs may be different, but I have a PR open with Nicola that I submitted a few minutes ago to add an extra examples page in. but I'd be happy to get any feedback on whether or not the solution I share using Caddy to help provide the static HTTP server functionality might be of some use for you:

* https://www.youtube.com/watch?v=M5UcJI8t4AI 
[![SFTPGo on Windows with Active Directory Integration + Caddy Static File Server Example](https://img.youtube.com/vi/M5UcJI8t4AI/0.jpg)](https://www.youtube.com/watch?v=M5UcJI8t4AI)

Please let me know (I apologize, the Youtube video is quite long and the Caddy part doesn't start until around minute 55 or so...currently Youtube is also still processing the higher resolution versions of the video so you may need to wait a few hours until those are available to see the instructions in the video in better detail).

(The PR I have open has a copy of the example Caddyfile configuration you might want to use as a starting point for the static HTTP server functionality that is essentially the same as the one I'm using in the video).

**Comment by NightMachinary** [comment]
@orware I already use Caddy; The problem is that caddy doesn’t see the virtual folders.

**Comment by drakkan** [comment]
Well, we now support [cloud based virtual folders](https://github.com/drakkan/sftpgo/commit/d6dc3a507ed56a794bb9f9c8a4fb3321eccb1c7b), and we can also mix local and local encrypted folders.

I don't know if I'll add this feature, anyway the first step is to find a good bootstrap file explorer theme.

Something like this [one](https://demos.devexpress.com/bootstrap/filemanager/) but free and well maintained.

Can you please help me to search a suitable theme? Thank you

**Comment by NightMachinary** [comment]
> Well, we now support [cloud based virtual folders](https://github.com/drakkan/sftpgo/commit/d6dc3a507ed56a794bb9f9c8a4fb3321eccb1c7b), and we can also mix local and local encrypted folders.
> 
> I don't know if I'll add this feature, anyway the first step is to find a good bootstrap file explorer theme.
> 
> Something like this [one](https://demos.devexpress.com/bootstrap/filemanager/) but free and well maintained.
> 
> Can you please help me to search a suitable theme? Thank you

Why don’t you just use Caddy’s theme? They have a go template for their file browser. I once copied a script that generated directory index HTML, which was forked from Caddy:

https://github.com/NightMachinary/.shells/blob/489ea350a49205d851d2c72e93746e3fedf24be5/scripts/python/dirindex_gen.py

**Comment by NightMachinary** [comment]
Another option might be Nextcloud. I don’t know hard it would be to adapt their code, but they certainly have a featureful file browser.

**Comment by orware** [comment]
@NightMachinary, maybe I misunderstood what you were asking for above (were you actually asking more for a file manager interface that users could login to with their SFTPGo credentials, and then access/manage their files via the web?)

If so, then I'm not sure if that's a future plan/idea Nicola has to include or not (the previous solution I was using, CrushFTP, did provide that via its "WebInterface" feature: https://www.crushftp.com/crush10wiki/Wiki.jsp?page=WebInterface). The way I had things setup for CrushFTP however, it was never a feature we really utilized much, so it's not something we're missing with the recent switch to SFTPGo in our case. 

With that in mind though I do get your point on the topic since it can definitely be helpful for users to not have to install a client at all and I wouldn't mind having it available as an additional option either, but it's not critical at the moment for my particular use case (I do like though that all of the big Operating Systems seem to include an integrated WebDAV client it seems from Nicola shared above, which would make that a potentially client-less option, even if it isn't a browser-based solution).

What I was using Caddy for in my video above was strictly for the files I wanted to have be publicly accessible, so using Caddy's file_server directive for that works well (but in that case I was pointing to the root folder that a bunch of public virtual folders are located in on the file system, and wasn't expecting / needing to have Caddy display the virtual folders themselves as they are being presented on the SFTPGo side of things with the virtual folder names).

**Comment by NightMachinary** [comment]
@orware No, I just want a static HTTP listing (just downloadable, nothing else). The problem is that I don’t have a root directory containing everything, my virtual directories point to dirs all over the place. I currently use symbolic links to fix this, but this makes me need to both add a symlink and a virtual folder for every new directory which is undesirable.

**Comment by orware** [comment]
Gotcha, thanks for the extra detail! That makes sense as to why it's a bit tricky to solve in your case.

I'm just curious, does the symlink option work as a solution in this case (aside from it requiring extra work as you mentioned, I'm just curious if it does work since I don't use them that much on my end).

**Comment by NightMachinary** [comment]
@orware It works perfectly for Caddy, but it doesn’t work with, e.g., sftpgo, which is the whole reason I am bothering with the virtual folders. macOS sucks; On Linux, I could just mount-bind the directories instead of symlinking them.

**Comment by drakkan** [comment]
@orware SFTPGo does not follow symbolic links outside the home directory for security reasons. If you set up a home directory you generally don't want to give access to files outside of that directory. So symbolic links work if they point to a file within the user's home directory. I'm not sure making it configurable is a good idea

**Comment by orware** [comment]
Thanks Nicola! I'm not planning on using symlinks for my use case but was just curious how others end up using them (I think in the few times I experimented with them, some things may not have worked as expected, but the need doesn't come up too much with what I usually work with).

**Comment by drakkan** [comment]
@NightMachinary thank you, I'll evaluate your suggestions, you could also evaluate an SFTP file browser, for example:

- https://www.filestash.app/
- https://github.com/Studio-42/elFinder
- https://www.monstaftp.com/download

Please note that I have not tested these projects and I'm not related in any way with them
