### ISSUE TITLE
Environement variable for httpd bindings

### ISSUE THREAD

**Issue by laurentAstonIf** [drakkan/sftpgo#407]
Hello

I'm migrating from v1 to V2 and i'm trying to override some default config values using env variable 
these are working well : 
SFTPGO_DATA_PROVIDER__DRIVER
SFTPGO_COMMON__DEFENDER__ENABLED
SFTPGO_COMMON__UPLOAD_MODE
SFTPGO_SFTPD__BINDINGS__0__PORT

and this one is not replaced 
SFTPGO_HTTPD__BINDINGS__0__PORT

from the json config file, both SFTPD and HTTPD seems to have the same bindings/port array
so i don't understand what i'm doing wrong.

i'm using v2.0.0.4

to reproduce you can use 
docker run --rm --name testgo -p 100:47536 -p 101:27563 -e SFTPGO_HTTPD__BINDINGS__0__PORT=47563 -e SFTPGO_SFTPD__BINDINGS__0__PORT=27563 -d "drakkan/sftpgo:v2.0.4"

on a browser localhost:100 is not working
you can see in the log 
SFTPD:{Banner:SFTPGo_2.0.4 Bindings:[{Address: Port:27563 
HTTPDConfig:{Bindings:[{Address: Port:8080 => not replaced

if you use
docker run --rm --name testgo -p 100:8080 -p 101:27563 -e SFTPGO_HTTPD__BINDINGS__0__PORT=47563 -e SFTPGO_SFTPD__BINDINGS__0__PORT=27563 -d "drakkan/sftpgo:v2.0.4"
on a browser localhost:100 is working
because it's using the default 8080 port

Do you have any idea ?

Thanks
Laurent
ps : i have also tried with SFTPGO_HTTPDConfig__BINDINGS__0__PORT=47563
as the log write HTTPDConfig:{Bindings vs SFTPD:{Bindings:

**Comment by drakkan** [comment]
Hi,

thank you for you report. 
This is a bug that was already fixed in the development version, in v2.0.4 the maximum port number that you can set using env vars is 32767, any integer > 32767 will not work. 

If you try the edge variant it works as expected. Since I'm finalizing v2.1.0 I don't know if I'll release a v2.0.5 with this fix or directly v2.1.0. If you don't want to use the edge variant, as temporary workaround, you can use a port <= 32767

**Comment by laurentAstonIf** [comment]
thanks !
