### ISSUE TITLE
ftp 450 Could not list: failure

### ISSUE THREAD

**Issue by alex1528** [drakkan/sftpgo#417]
Passive Mode on

450 Could not list: failure 

目录下的文件数1w+

**Comment by drakkan** [comment]
Hi,

please ask questions or report issues in english, wrote the SFTPGo version you are using and post the sftpgo logs, thank you

**Comment by drakkan** [comment]
I tryed translating from chinese, I don't know what means number of files 1w+. I just tested listing a folder with 100000 files and it works fine. I can only guess here, I suppose you are running an old SFTPGo version (built using Go 1.15 or lower) and you are trying to list a directory on a cifs share: this will not work, it is a Go bug fixed in Go 1.16, recent SFTPGo versions are built using Go 1.16.

Please reopen providing more info if the issue persist, thank you
