### ISSUE TITLE
v2 problem with go modules

### ISSUE THREAD

**Issue by skozlov404** [drakkan/sftpgo#443]
Due to the [Go modules v2 problem](https://donatstudios.com/Go-v2-Modules), the package is not updated on pkg.go.dev since version 1.2.2: https://pkg.go.dev/github.com/drakkan/sftpgo. Also, because of this - `go get` by default downloads version 1.2.2, and downloading v2.0.4 forcefully is not possible:
```
$ go get github.com/drakkan/sftpgo@v2.0.4
go get: github.com/drakkan/sftpgo@v2.0.4: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

**Comment by drakkan** [comment]
Hi,

I'm aware of this issue. Even if I add v2 support `go get` will still fail since it does not honor the `replace` directive. 

I'll consider this once my patches are merged upstream and we no longer need any replace directive within `go.mod`.

However SFTPGo is an application, not a library. I don't want to support its use as a library. It is not meant to be embedded in your application (possibly violating the AGPLv3 license)
