### ISSUE TITLE
Web client not working on edge container

### ISSUE THREAD

**Issue by ryjogo** [drakkan/sftpgo#456]
Have tried drakkan/sftpgo:edge-alpine and drakkan/sftpgo:v2.1.0 but it seems the endpoint for web/client doesn't exist, should it? I have not set the vars to disabled, they are enabled by default right?

**Comment by drakkan** [comment]
Hi,

yes it should work by default, please post the sftpgo startup logs, thank you

**Comment by ryjogo** [comment]
sure 
[container_sftpgo.log](https://github.com/drakkan/sftpgo/files/6670185/container_sftpgo.log)

**Comment by drakkan** [comment]
You are likely using an outdated configuration file, from your logs:

```
HTTPDConfig:{Bindings:[{Address:0.0.0.0 Port:8080 EnableWebAdmin:true EnableWebClient:false
```

**Comment by drakkan** [comment]
If you are configuring from env vars this could be fixed in https://github.com/drakkan/sftpgo/commit/62744e081b17b9674f3fadbbc6c100306983212b

If instead you are using a config file and the `enable_web_client` key is missing you have to adapt your configuration files as suggested in the release notes

**Comment by ryjogo** [comment]
ah yes, i removed the json now and will just use env vars exclusive. thanks.
