### ISSUE TITLE
Logging configuration

### ISSUE THREAD

**Issue by gsbhamra** [drakkan/sftpgo#465]
Hello,
My apologies if this is trivial or has been previously asked/resolved. I have tried searching for logging options but havent't come across anything.

I am trying to figure out how I can configure logging options in sftpgo.json file in /etc/sftpgo

While searching, there are examples on how to go about setting logging parameters when manually starting sftpgo process but have not been able to figure out to configure it in the config file.

So when I reboot the server etc., the sftpgo process is started automatically. All other setting from sftpgo.json work, however I am lost when trying to configure the logging.

Any help would be greatly appreciated.

Regards,

**Comment by drakkan** [comment]
Hi,

logging configuration options are configurable via CLI arguments or env vars, they are documented [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md). Logging is not configurable from `sftpgo.json` (or any other supported configuration file format) because if we are unable to load the configuration file we cannot properly log the error.

If you are on Linux, and you are using an official package, a convenient way to pass the logging configuration is to add it to `/etc/sftpgo/sftpgo.env`, for example:

```shell
cat /etc/sftpgo/sftpgo.env 
SFTPGO_LOG_FILE_PATH=/srv/sftpgo/logs/sftpgo.log
```

the systemd service will read env vars from this file
