### ISSUE TITLE
unable to login to web admin console after upgrade

### ISSUE THREAD

**Issue by perfecto25** [drakkan/sftpgo#513]
Hello IM running sftpgo on Centos 7 x64

i upgraded from 2.0.1 to 2.1 (latest), copied over the backed up /var/lib/sftpgo/sftpgo.db (sqlite) and /etc/sftpgo/sftgo.json

service starts up, but I am unable to login with my admin account, getting this in the browser,

**unable to verify form token: token is unauthorized**

all my ssl keys and certs are the same. Am I missing something?

**Comment by drakkan** [comment]
Hi,

the error you posted is related to the CSRF token and happens if you load the admin page and submit the login form after restarting SFTPGo. If you upraded using the RPM the sftpgo.db is not overwritten. However the db is migrated when you start the new version. Regarding the configuration file you have to apply your customization on the top of the new configuration file.

Please note that v2.1.0 has both a web admin and a web client UI. Please make sure you are logging in to the URL `/web/admin/login`. This confusing behaviour is already fixed in the development version and it will be included in v2.2.x

![webadmin](https://user-images.githubusercontent.com/553263/130247895-2d19293a-52d2-4fa2-bb1f-7c07fc24ecd8.png)

![webclient](https://user-images.githubusercontent.com/553263/130247915-d2037cd9-8858-46b4-b30c-dc1a00050cd1.png)

**Comment by perfecto25** [comment]
got it, thanks for the quick response,

I ended up yum remove sftpgo, reinstalled the 2.1 rpm, and copied back the json and db files, (had to recreate my admin login)

but all the user accounts are there and working now. 

Thanks for all the hard work on this package, saved me so much headache as compared to running vsftpd

https://perfecto25.medium.com/goftp-the-vsftpd-on-steroids-19b2d3c5dde8

**Comment by drakkan** [comment]
> got it, thanks for the quick response,
> 

It is strange that you have to recreate your admin, v2.0.x and 2.1.x should be compatible.

> I ended up yum remove sftpgo, reinstalled the 2.1 rpm, and copied back the json and db files, (had to recreate my admin login)
> 
> but all the user accounts are there and working now.
> 
> Thanks for all the hard work on this package, saved me so much headache as compared to running vsftpd
> 
> https://perfecto25.medium.com/goftp-the-vsftpd-on-steroids-19b2d3c5dde8

great post, thanks! vsftpd only supports the old FTP protocol, with SFTPGo you can use SFTP/FTP/WebDAV and also an HTTP based client (the development version also supports writes from the web client)

**Comment by drakkan** [comment]
Thank you for sponsoring the project, much appreciated
