### ISSUE TITLE
Google Cloud Storage + rsync

### ISSUE THREAD

**Issue by niedermaiera** [drakkan/sftpgo#542]
Hey there

I spend a ton of hours this week to get SFTPGo running with rsync but I cannot figure out what I am still doing wrong. For storage I **do not use local storage** but a Google Cloud Storage.

Is this working at all or should I stop trying?

When I sync a single file the log shows me nothing bad:
```
$ rsync -av test.txt --progress test@test.com
sending incremental file list

sent 68 bytes  received 12 bytes  160.00 bytes/sec
total size is 0  speedup is 0.00
```
But no file appears.

Thanks for your help :-)

**Comment by drakkan** [comment]
Hi,

short answer: this will not work, stop trying.

Long answer: rsync does not support SFTP it sends data to the remote rsync executable over SSH. The remote rsync executable works on local filesystem only. This is documented [here](https://github.com/drakkan/sftpgo/blob/main/docs/ssh-commands.md).

I suggest to replace `rsync` with a more modern alternative. You might consider to use SFTPGo as SFTP backend for [rclone](https://rclone.org/sftp/) instead of `rsync`, this way there are no limitations and `rclone` does not need to be installed on the server side since it uses the SFTP protocol. I'll add this to the docs.

You can use rclone to sync data directly to your cloud backend but this way rclone does not know about SFTPGo virtual folders, permissions, etc. this is why I suggest using SFTPGo as SFTP backend for rclone.
