### ISSUE TITLE
static pre-startup configuration

### ISSUE THREAD

**Issue by flokli** [drakkan/sftpgo#611]
From some tinkering, I really like SFTPGo. Thanks for developing it!

I'd like to use SFTPGo in a more static setup, where sftpgo is configured "from the outside".
I'd like to run it in kubernetes, passing in all configuration as a configmap.
This should include user config, folder config and mapping, so there's no need to access the admin interface to create user afterwards, add ssh pubkeys etc.

Ideally, the admin interface wouldn't be available at all, and no change of these settings is possible.

Is this something that's supported right now, or you're planning to support?

**Comment by drakkan** [comment]
Hi,

yes this should work, you can prepare a configuration dump from a test instance (from the Maintenance section you can export a dump) and then load it. The memory provider should be the ideal choice for this use case since it can directly load a config dump. You can also use any other supported provider and load you config as initial data. You can disable the web admin UI. All the configuration parameters are available as env vars too.
No time for a step by step guide, please check the docs, thanks

**Comment by flokli** [comment]
Thanks for the quick reply! I'll take a look, and probably add something to the docs :-)

Just to make sure I understand - this would be setting `SFTPGO_LOADDATA_FROM` to an exported json, which was previously retrieved from `$adminInterface/web/admin/backup?output-data=1`?

And the only way to change any of the state in that backup could be done from the admin interface?

**Comment by drakkan** [comment]
`SFTPGO_LOADDATA_FROM` is a way, another way is to use the memory provider, it can load the dump file directly, take a look at the "data provider" section [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md). 

You can disable the admin UI or disable the whole HTTPD service and so also the REST API, this is explained in the doc linked above.

If you disable the entire HTTPD service the only way to change the configuration is to log into the server/container and change the data provider directly.

The JSON dump can also be generated manually but I suggest to use a test SFTPGo instance and take a backup from there, this way if you update SFTPGo the test instance data is automatically updated and you can simply generate a new dump file suitable for the new version instead of manually editing a JSON file

If you want to provide a howto for this setup it might be useful to others, thanks

**Comment by drakkan** [comment]
Please re-open if you have other questions. Static setups are supported
