### ISSUE TITLE
concurrent testing log print error too many open files

### ISSUE THREAD

**Issue by sxj1991** [drakkan/sftpgo#622]
I use sftpgo-version 2.0.4 , I concurrent testing number 1000，I get message 
![image](https://user-images.githubusercontent.com/51181987/143539189-8b7c5124-d776-49d1-ae26-3b1d16856352.png)

if you know why please tell me thanks

**Comment by drakkan** [comment]
You have to increase the open file limit, take a look here

http://woshub.com/too-many-open-files-error-linux/
https://stackoverflow.com/questions/29403185/docker-error-too-many-open-files

**Comment by drakkan** [comment]
The next time please open a new issue instead of editing an existing one describing a completly different issue.

This report seems similar to this [one](https://github.com/drakkan/sftpgo/issues/479).

Not related to this issue but please note that 2.0.4 is not supported anymore. Only the latest stable branch (currently 2.2.x) and the development version are supported
