### ISSUE TITLE
Feature request: implement Docker registry 

### ISSUE THREAD

**Issue by v-trn** [drakkan/sftpgo#627]
Hello!

It would be nice, if you implement OCI Distribution Specification for storing and distributing container images https://github.com/distribution/distribution so you can expand the target audience (interested in fine-grained access control and other futures of your project)

**Comment by drakkan** [comment]
Hi,

I admit I read the above documentation quickly, it is not clear to me what I need to change to support the OCI specification. Do you know of another project that implements it? At the moment we add some labels, take a look [here](https://github.com/drakkan/sftpgo/blob/main/.github/workflows/docker.yml#L153). Do you have a concrete use case so that I can test a non-working scenario myself? Thanks

**Comment by drakkan** [comment]
Please reopen providing more info and a concrete use case, thanks
