### ISSUE TITLE
KMS Encryption configurability

### ISSUE THREAD

**Issue by mike-k0** [drakkan/sftpgo#630]
https://github.com/drakkan/sftpgo/blob/main/docs/kms.md#local-provider

Above states that KMS uses Secretbox for authentication with some backwards support for `AES-256-GCM` in older versions. Is it possible to set encryption to `AES-256-GCM` for KMS in 2.x+?

**Comment by drakkan** [comment]
Hi,

it is not supported anymore. I replaced a self made encryption based on AES-256-GCM with an external library esplicitally designed to encrypt secrets. Please note that if you don't configure a master key, anyone that can get the data from your dataprovider can, with some effort, decrypt them.

**Comment by darkdatter** [comment]
@drakkan Which library are you using for secret encryption?

**Comment by drakkan** [comment]
ops ... I was wrong the revisited buitin provider using AES-256-GCM is still there. Please check the updated docs. I suggest to use the local provider with a master key instead.

**Comment by drakkan** [comment]
> @drakkan Which library are you using for secret encryption?

this [one](https://pkg.go.dev/golang.org/x/crypto/nacl/secretbox) included in Go that implements [NaCL](https://nacl.cr.yp.to/secretbox.html)

**Comment by mike-k0** [comment]
Just curious @drakkan , but is there a specific rationale that using `builtin://` and AES-256-GCM is not recommended? Is this something that is planned to be deprecated?

**Comment by drakkan** [comment]
because this is a self made encryption algo based on AES-256-GCM. The one included in Go is specifically designed to encrypt small strings and is widely used and verified. I think NaCL is the same algorithm used in libsodium for example.

I'm not sure if deprecate AES-256-GCM in future, to be useful it should support master key at least but this could break some old installations
