### ISSUE TITLE
Issue with S3 compatible instance (Minio) and self signed certificates

### ISSUE THREAD

**Issue by remiborredon** [drakkan/sftpgo#643]
Hello,

I'm working on a project in which I need to send a file to a sftp server and store it in a Minio instance using S3. I configured sftpgo to use my S3 endpoint but when I connect to the server (using winscp), I obtain the following error:

`General failure (server should provide error description).
Error code: 4
Error message from server: failure: RequestError: send request failed
caused by: Get "https://192.168.10.2:10444/testbucket?delimiter=%2F&list-type=2&prefix=": x509: certificate signed by unknown authority

Common reasons for the Error code 4 are:
- Renaming a file to a name of already existing file.
- Creating a directory that already exists.
- Moving a remote file to a different filesystem (HDD).
- Uploading a file to a full filesystem (HDD).
- Exceeding a user disk quota.
`

I suppose this is due to the fact that my CA is a self signed CA. I checked in https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md but I did not find the way to solve my issue.

By the way, the option to use Let's encrypt to obtain a free certificate is not available for me as my setup is not supposed to be connected to internet.

Could someone explain me how to add my sel-signed certificate ?

Thanks in advance,

Rémi

**Comment by drakkan** [comment]
Hi,

this is an OS level issue rather than an SFTPGo issue. You simply need to add your root CA to the trusted ones.

I did a quick test on Arch Linux. I used certstrap to generate the certificates, you can use any other way (openssl commands or other tools)

```
./certstrap-dev-14dbcb06-linux-amd64 init --common-name "Cert Auth"
./certstrap-dev-14dbcb06-linux-amd64 request-cert --domain localhost --ip 127.0.0.1 --common-name localhost
./certstrap-dev-14dbcb06-linux-amd64 sign localhost -CA "Cert Auth"
```

I copied the generated certificate and key to minio folder (renaming them):

```
ls -la /var/lib/minio/.minio/certs/
totale 20
drwx------ 3 minio minio 4096  5 nov 18.27 .
drwx------ 3 minio minio 4096 30 dic  2019 ..
drwx------ 2 minio minio 4096 30 dic  2019 CAs
-r--r----- 1 minio minio 1675  8 dic 18.28 private.key
-r--r--r-- 1 minio minio 1537  8 dic 18.28 public.crt
```

finally I copied the root CA to the trust store (this is the important part):

```
cp out/Cert_Auth.crt /etc/ca-certificates/trust-source/anchors/
update-ca-trust
```

and then restart both SFTPGo and MinIO. On debian based distro I think you have to use `update-ca-certificates` instead of `update-ca-trust`.

If you are on docker take a look here:

https://stackoverflow.com/questions/42292444/how-do-i-add-a-ca-root-certificate-inside-a-docker-image

**Comment by remiborredon** [comment]
Hello,

Thanks a lot for this quick and precise support!

Best resgards,

Rémi Borredon
TCMS Engineer

Alstom Crespin SAS
1 Place des ateliers - 59154 Crespin - France
Bureau :  +33 (0) 3 27 23 32 45
Mobile  : +33 (0) 6 28 40 25 76
Courriel: ***@***.******@***.***>
www.alstom.com<http://www.alstom.com/>

***@***.***           ***@***.***    ***@***.***    ***@***.***    ***@***.***    ***@***.***

**Comment by drakkan** [comment]
Please reopen if you have other questions/issues, thanks
