### ISSUE TITLE
Telemetry port on v.2.2.1

### ISSUE THREAD

**Issue by ryjogo** [drakkan/sftpgo#659]
Hi, it seems i have to declare the telemetry port instead of relying on the default "1000" now? Not an issue, but an observation - could it be the default is not being applied any more?

          - name: SFTPGO_TELEMETRY__BIND_PORT
            value: '10000'

**Comment by drakkan** [comment]
Hi,

the default was changed to [0](https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L241) and so telemetry is disabled by default. This has been changed to reduce the possibility of SFTPGo not starting because the port is already in use by another service. I should have documented it in the release notes

**Comment by ryjogo** [comment]
Ah that explains it, i guess the documentation should be updated too. 

Thanks :)
