### ISSUE TITLE
Question: Do S3 backends use multipart uploads/downloads for large files?

### ISSUE THREAD

**Issue by voidpls** [drakkan/sftpgo#694]
For >500MB-ish files, are multipart uploads taken advantage of between SFTPGo and the S3 backend?

**Comment by drakkan** [comment]
Yes. I think you haven't installed/tested SFTPGo, it is quite clear if you create an s3 user

**Comment by voidpls** [comment]
I have, just not the S3 backend. Sorry about that - the backend I was looking at has a minimum monthly charge.

**Comment by drakkan** [comment]
Sorry for being rude, many people are not interested in SFTPGo, they ask questions here and through private e-mails just to better understand the SFTPGo code and copy it into their proprietary applications (violating the license) and that makes me nervous. 

The multipart uploads/downloads support is one of the most asked questions since it is not so simply to receive data via SFTP/FTP etc and uploads to S3 using the multipart feature. Many libraries out of there just set the concurrency to 1 or have bugs.

Regarding your question, just give a look at the [getting started guide](https://github.com/drakkan/sftpgo/blob/main/docs/howto/getting-started.md#Creating-users-with-a-Cloud-Storage-backend). When you configure an S3 user you can set the upload/download part size and concurrency. It is also recommended to set an appropriate download timeout for individual parts.

**Comment by voidpls** [comment]
No worries, thank you for the explanation, I'll refer to the guide from now on
