### ISSUE TITLE
Action execution question

### ISSUE THREAD

**Issue by audouts** [drakkan/sftpgo#703]
I have some scripts running after transfers complete. During a test, I noticed that one of the tasks didn't happen.

Is it possible the script was stopped because of another operation? Do the actions execute on their own threads?

I may have made a mistake in my logic, so I want to review it. But I wonder what happens if a script does something like `sleep 10` and meanwhile, the action is invoked again by another user.

**Comment by drakkan** [comment]
Hi,

Scripts can be run [synchronously](https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L7) or asynchronously depending on the configuration. 

In any case SFTPGo cannot leak file descriptors because the external script has a bug so there is an execution timeout (30 seconds). If your script can take longer you can explicitly fork a child process.

SFTPGo can only terminate the script if it takes longer than the defined timeout. You can find more details in your logs, you should see something like this each time a script is executed:

```
{"level":"debug","time":"2022-01-29T09:41:57.088","sender":"SFTP","message":"executed command \"/tmp/test.sh\", elapsed: 30.007977803s, error: signal: killed"}
```

in this case test.sh does sleep 40 and so it is killed

**Comment by drakkan** [comment]
Please reopen or comment here if you have other questions, thanks
