### ISSUE TITLE
portable mode sftpgo.db error

### ISSUE THREAD

**Issue by enescakir** [drakkan/sftpgo#73]
I build `sftpgo` docker image with alpine instructions.

I am trying to start server with `sftpgo portable`, but it throws `ERR error initializing data provider: stat sftpgo.db: no such file or directory` error all the time. 

I investigated the code and portable mode selects `memory` data provider. Unfortunately I could not find the bug.

**Comment by drakkan** [comment]
Hi, 

I think you should change `docker-entrypoint.sh` here:

https://github.com/drakkan/sftpgo/blob/master/docker/sftpgo/alpine/docker-entrypoint.sh

please try to remove the serve option there and add `portable` instead. 

The real fix should be to change the alpine dockerfile in a way similar to the debian one: `serve` should be removed from the entrypoint and setted in CMD so that it can be overridden using docker CLI.

A pull request is welcome, otherwise I'll fix it myself later today, thanks

**Comment by enescakir** [comment]
I wrote my own `entrypoint` and overwrite default one. I think problem isn't about `entrypoint`. When I start in portable mode,  it checks existence of `sftpgo.db`. I opened a PR. #74

**Comment by enescakir** [comment]
> The real fix should be to change the alpine dockerfile in a way similar to the debian one: `serve` should be removed from the entrypoint and setted in CMD so that it can be overridden using docker CLI.

Also I create a PR #75 for this
