### ISSUE TITLE
Allow to set Password Policy

### ISSUE THREAD

**Issue by lispstudent** [drakkan/sftpgo#912]
I am volunteering for a small non-profit. We discovered `sftpgo` just recently and started using it instead of proFTPd on a FreeBSD server. It is wonderful.

Our users are all non-technical, serving in the humanities-related field. I know for sure if we give acess to the Web Client and allow them to change passwords, they will all use simple, easily guessable ones. Even if we would activate `defender`, I am still concerned that some accounts would be hacked into.

Would it be possible to allow the admin to set a Password Policy, like minimum length, lowercase/uppercase/symbols, digits, etc?

Or at least for the time being having an option to prohibit password change (maybe just hiding the option in the Web Client)?

Thank you for this gem of a software. It covers our use-case perfectly, with elegance and performance!

**Comment by drakkan** [comment]
Hi,

both options are already supported. You can disable password change from the admin UI

![disable-pwd-change](https://user-images.githubusercontent.com/553263/177978146-408350ef-bae0-45db-b2e4-607f31b22ccd.png)

so users cannot change password from the web client.

Or you can set a password policy [here](https://github.com/drakkan/sftpgo/blob/main/sftpgo.json#L221). Take a look at the docs [here](https://github.com/drakkan/sftpgo/blob/main/docs/full-configuration.md). I prefer an [entropy value](https://github.com/wagslane/go-password-validator#what-entropy-value-should-i-use) instead of the classical min lenght etc

You can also force your users to setup 2FA

**Comment by lispstudent** [comment]
Wow, I thought I studied the manual carefully. Thank you for pointing those out and replying so promptly.

Thank you again, your software has become a pillar for us.

Please feel free to close the ticket on your side whenever you wish.

**Comment by tooptoop4** [comment]
@lispstudent did u workout how to set password-change-disabled via configuration file?

**Comment by lispstudent** [comment]
Hi, at the moment we are using `filestash` as frontend to `sftpgo`, since we need a bit more flexibility for end-users. Password-change policy is managed there.
