### ISSUE TITLE
sql_table_prefix not working on specific tables

### ISSUE THREAD

**Issue by LindezaGrey** [drakkan/sftpgo#937]
Hi there,

when i create a new environment, with Docker (v2.3.1-alpine) and a postgres database (postgres:13-alpine), on some tables the prefix is missing (i.e. prefix is "sftpgo_"):

![image](https://user-images.githubusercontent.com/39629455/180754172-ef37c6f9-496e-4433-bd56-9aed66d02f12.png)

**Comment by drakkan** [comment]
Hi,

this bug was already noted and [fixed](https://github.com/drakkan/sftpgo/commit/b3ca20b5e6c0e7601d9c49a79bf81b793c5558a9).

The fix will be included in v2.3.2. To avoid a backward incompatible change once v2.3.2 will be released, I suggest to use the 2.3.x branch (v2.3 + bug fixes) for now.

You can download a recent build artifact for your OS from [here](https://github.com/drakkan/sftpgo/actions/runs/2726357838) or you can use a 2.3.x tag if you are on docker

**Comment by LindezaGrey** [comment]
Alright, thanks for the quick reply! :)
